{
  "comments": [
    {
      "key": {
        "uuid": "a18d77c4_28b929d6",
        "filename": "client/run_isolated.py",
        "patchSetId": 5
      },
      "lineNbr": 729,
      "author": {
        "id": 1001385
      },
      "writtenOn": "2020-08-04T09:18:35Z",
      "side": 1,
      "message": "Are you sure this is the right bug number?",
      "range": {
        "startLine": 729,
        "startChar": 39,
        "endLine": 729,
        "endChar": 46
      },
      "revId": "69c5a363aff7d87762e0bbc0783fd59a968cbfe7",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}